### ISSUE TITLE
GKE worker node needs bucket level permissions

### ISSUE THREAD

**Issue by lewanbla** [GoogleCloudPlatform/gcs-fuse-csi-driver#27]
Before mounting a bucket one has to bind to the bucket IAM in fact two service accounts:
- first - related to a workload, bound to k8s serviceaccount object
- second - service account of GKE node (with at least roles/storage.objectAdmin)

This implies, that the content of the bucket can be accessible by other k8s workloads using GKE node service account. This usage is not straighforward, but highly possible. Is there anything that can be done with this privilliges and principles overlapping? From security point of view this is not acceptable. The best case scenario is binding only one service account - workload related.

**Comment by songjiaxun** [comment]
Actually, you do not need to grant the GKE node service account any permissions.

Since the CSI driver relies on the GKE Workload Identity feature, you can create one workload related GCP service account, bind the GCP SA with your Kubernetes SA, and use your Kubernetes SA as the GCP SA. The GCP SA does not need to be the GKE node default SA. Please see [Set up access to Cloud Storage buckets via GKE Workload Identity](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/usage.md#set-up-access-to-cloud-storage-buckets-via-gke-workload-identity) for details.

If a user accidentally grants the GKE node service account permission to access the bucket, we consider this behavior as a user-misconfiguration, and we cannot prevent users from doing it, regardless of that this is highly discouraged.
