### ISSUE TITLE
Usage of privileged pod in driver

### ISSUE THREAD

**Issue by schrodit** [GoogleCloudPlatform/gcs-fuse-csi-driver#45]
Hey, 

I have a quick implementation related question:

Most of the csi drivers need privileged access as they are using mount (with optional some kernel modules. e.g. ceph).
Means that they need the CAP_SYS_ADM in order to do mounting in Linux.
Fuse on the other hand is build to not need such privileges and only mount in user space.
So I'm wondering why does this csi-driver need to run a [privileged container](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/deploy/base/node/node.yaml#L45)?

**Comment by songjiaxun** [comment]
Thanks for the question.

The CSI driver container needs to be a privileged container due to the following reasons:

1. To open the `/dev/fuse` device on the host VM requires privilege.
2. And more importantly, the CSI driver mounts volumes under the host path `/var/lib/kubelet/pods`. In order to make the mount/umount operations done inside the CSI container reflected on the host VM, the path `/var/lib/kubelet/pods` is mounted to the CSI driver using mountPropagation `Bidirectional`. According the Kubernetes documentation, `Bidirectional` is allowed only in privileged containers. See https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation.

**Comment by schrodit** [comment]
@songjiaxun thanks for the detailed explanation. That was really helpful.

Just one follow up question:
I see now why the container needs privileged. But I also see that both images (the driver and mounter) run as root user.
Is this also required or would it be possible to run the binaries as a different non-root user?

**Comment by songjiaxun** [comment]
The root user is also required. The CSI driver and the mounter binary need to run as a root user to have access to the path `/var/lib/kubelet/pods` and create subdirectory under it, because the path `/var/lib/kubelet/pods` was created by the root user.

**Comment by schrodit** [comment]
Thanks a lot for the explanation.
